name: 'Setup Verilator'
description: 'Download, build, and cache Verilator'

inputs:
  verilator-version:
    description: 'Verilator version to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install verilator run-time deps
      shell: bash
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
        sudo apt-get install help2man perl python3 make libfl2 libfl-dev zlib1g zlib1g-dev libclang-dev

    - name: Cache Verilator
      id: cache-verilator
      uses: actions/cache@v4
      with:
        path: ~/verilator
        key: verilator-${{ inputs.verilator-version }}
        restore-keys: |
          verilator-

    - name: Download and Build Verilator
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get -y install autoconf flex bison
        cd ${{ runner.temp }}
        git clone https://github.com/verilator/verilator.git verilator_git
        cd verilator_git
        git checkout ${{ inputs.verilator-version }}
        autoconf
        rm -rf "$HOME/verilator"
        ./configure --prefix "$HOME/verilator"
        make -j "$(nproc)"
        make install

    - name: Setup Verilator Path
      id: setup-path
      shell: bash
      run: |
        echo "$HOME/verilator/bin" >> $GITHUB_PATH
